name = "Christian Guzman Personal Theme"
license = "MIT"
licenselink = "https://github.com/h-4vok/personal-brand-website-theme/blob/main/LICENSE"
description = "The custom CSS-heavy Hugo presentation layer used for christianguzman.uk, focused on Christian Guzmanâ€™s portfolio and editorial work."
homepage = "https://christianguzman.uk"
demosite = "https://christianguzman.uk"
tags = ['personal-brand', 'portfolio', 'journal', 'css-focus', 'responsive', 'christian-guzman', 'landing-page', 'blog', 'dark', 'clean', 'agency']
features = ['bootstrap','responsive']
min_version = "0.147.2"

[author]
  name = "Christian Guzman"
  homepage = "https://christianguzman.uk"
